default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password:  #<-- which you have defiend while installing postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development


test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  # username: username
  # password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>

